//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist
    {
        public int id_playlist { get; set; }
        public int id_usuario { get; set; }
        public int id_musica { get; set; }
        public Nullable<bool> curte { get; set; }
        public Nullable<bool> remove_curte { get; set; }
        public Nullable<bool> bloqueia { get; set; }
        public Nullable<bool> remove_bloqueia { get; set; }
    
        public virtual musica musica { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
