//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacionado
    {
        public int id_relacionado { get; set; }
        public int id_artista { get; set; }
        public int id_artista_relacionado { get; set; }
    
        public virtual artista artista { get; set; }
    }
}
