//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguir
    {
        public int id_seguir { get; set; }
        public int id_usuario { get; set; }
        public int id_artista { get; set; }
        public Nullable<bool> segue { get; set; }
        public Nullable<bool> remove_segue { get; set; }
        public Nullable<bool> bloqueia { get; set; }
        public Nullable<bool> remove_bloqueia { get; set; }
    
        public virtual artista artista { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
